version: '3'
services:
  sut:
    env_file:
      - .env
    build:
      context: .
      args:
        jdbc_driver_version: ${jdbc_driver_version}
    command: /opt/test_liquibase_mysql/run_test.sh
    depends_on:
      - mysql_db
    image: liquibase-mysql:build
  mysql_db:
    image: mysql/mysql-server
    container_name: mysql_db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: liquibase
      MYSQL_USER: liquibase
      MYSQL_PASSWORD: liquibase
    ports:
      - 3306:3306
